node {
    checkout scm
    dir('vote'){

        docker.withRegistry('https://jpaisregistry.azurecr.io', 'jpais-registry') {
            def voteImage = docker.build("voting-vote:${env.BUILD_ID}") 

            voteImage.push()
            voteImage.push('latest')
        }
    }
}